# Taula pregunta respostes Programació
PreResProg = [
    ["Què és HTML?", "Un llenguatge de programació", "Un llenguatge de marcat", "Un sistema operatiu", "Un navegador web"],
    ["Què significa CSS?", "Cascading Style Sheets", "Creative Style Syntax", "Computer Style System", "Custom Style Source"],
    ["Per a què serveix JavaScript?", "Per gestionar servidors", "Per fer càlculs matemàtics", "Per estilitzar pàgines web", "Per afegir interactivitat a les webs"],
    ["Quina extensió tenen normalment els arxius HTML?", ".htm", ".html", ".web", ".page"],
    ["Quina d’aquestes és una estructura de control?", "div", "if", "font", "href"],
    ["Quina diferència hi ha entre '==' i '===' a JavaScript?", "Cap diferència", "Comparació estricta vs comparació flexible", "Són operadors aritmètics", "Són funcions de classe"],
    ["Què fa un 'for loop'?", "Declara una variable", "Repeteix instruccions", "Crea una funció", "Importa llibreries"],
    ["Quin d’aquests no és un llenguatge de programació?", "Python", "Scratch", "Linux", "Java"],
    ["Què és una funció?", "Un tipus de dada", "Un mètode per repetir codi", "Una variable", "Una etiqueta HTML"],
    ["Què és Git?", "Un sistema de control de versions", "Un tipus de servidor", "Un llenguatge de programació", "Un editor de codi"],
    ["Quina d’aquestes és una llibreria de Python?", "Pandas", "Vue", "React", "Laravel"],
    ["Per a què serveix SQL?", "Per dissenyar webs", "Per gestionar bases de dades", "Per fer gràfics", "Per fer jocs"],
    ["Quin d’aquests és un sistema operatiu?", "Windows", "Java", "HTML", "CSS"],
    ["Per què serveix el comandament 'print()' a Python?", "Per imprimir a la pantalla", "Per guardar un arxiu", "Per començar un bucle", "Per llegir dades"],
    ["Quin és l’ús de '<head>' en HTML?", "Conté el contingut visible", "Conté metadades i enllaços", "Mostra imatges", "Executa codi JavaScript"],
    ["Què és una variable?", "Un número", "Una dada canviant", "Un tipus d’error", "Una funció"],
    ["Quina diferència hi ha entre 'let' i 'const' a JavaScript?", "'let' és per constants", "'const' pot canviar", "'let' pot canviar", "No hi ha diferència"],
    ["Com es comenta una línia a Python?", "// comentari", "# comentari", "<!-- comentari -->", "/* comentari */"],
    ["Quin d’aquests és un bucle?", "while", "with", "def", "class"],
    ["Com es defineix una funció a Python?", "function nom()", "def nom():", "func nom()", "define nom()"],
    ["Per a què serveix 'return' en una funció?", "Per començar la funció", "Per declarar variables", "Per retornar un valor", "Per acabar un bucle"],
    ["Quina etiqueta HTML crea un enllaç?", "<link>", "<a>", "<href>", "<url>"],
    ["Quin d’aquests no és un navegador web?", "Chrome", "Firefox", "Safari", "Visual Studio"],
    ["Què fa un servidor web?", "Mostra webs als usuaris", "Dibuixa imatges", "Edita vídeos", "Tradueix textos"],
    ["Com es crea un objecte a JavaScript?", "var obj = {}", "function obj()", "object.create()", "obj = []"],
    ["Quina estructura guarda múltiples valors?", "variable", "array", "comentari", "funció"],
    ["Com s’escriu un condicional en Python?", "if x > 0:", "cond x > 0", "x > 0 then", "if x > 0 then"],
    ["Com es concatena text en Python?", '"Hola" + " món"', '"Hola", "món"', '"Hola" & "món"', '"Hola" . "món"'],
    ["Per a què serveix 'console.log' en JavaScript?", "Per mostrar errors", "Per mostrar missatges al navegador", "Per crear variables", "Per importar dades"],
    ["Què fa un framework?", "Automatitza tasques de programació", "Són només estils visuals", "Només funciona amb bases de dades", "És un tipus d’antivirus"],
]

# Taula de respostes correctes Programació
ResCorProg = [
    "Un llenguatge de marcat",
    "Cascading Style Sheets",
    "Per afegir interactivitat a les webs",
    ".html",
    "if",
    "Comparació estricta vs comparació flexible",
    "Repeteix instruccions",
    "Linux",
    "Un mètode per repetir codi",
    "Un sistema de control de versions",
    "Pandas",
    "Per gestionar bases de dades",
    "Windows",
    "Per imprimir a la pantalla",
    "Conté metadades i enllaços",
    "Una dada canviant",
    "'let' pot canviar",
    "# comentari",
    "while",
    "def nom():",
    "Per retornar un valor",
    "<a>",
    "Visual Studio",
    "Mostra webs als usuaris",
    "var obj = {}",
    "array",
    "if x > 0:",
    '"Hola" + " món"',
    "Per mostrar missatges al navegador",
    "Automatitza tasques de programació",
]


# Taula pregunta respostes Matematiques
PreResMat = [
    ["Si tens 3 pomes i compres 4 més, quantes pomes tens en total?", "5", "6", "7", "8"],
    ["En Joan té 12 euros i en gasta 5. Quants euros li queden?", "6", "7", "8", "5"],
    ["Una bicicleta costa 120 €. Si tens 100 €, quant et falta?", "10", "20", "25", "30"],
    ["Si una caixa té 6 galetes i tens 3 caixes, quantes galetes tens?", "18", "16", "12", "20"],
    ["Tens 50 € i compres una joguina de 35 €. Quant et sobra?", "15", "20", "10", "12"],
    ["Si hi ha 5 taules i cada taula té 4 potes, quantes potes hi ha en total?", "20", "18", "16", "24"],
    ["En Marc llegeix 8 pàgines cada dia. Quantes pàgines llegirà en 5 dies?", "35", "40", "30", "45"],
    ["Una capsa conté 9 bolígrafs. Quants bolígrafs hi ha en 4 capses?", "36", "30", "32", "34"],
    ["Si un paquet pesa 2 kg i en tens 6, quin és el pes total?", "10", "12", "14", "8"],
    ["Hi ha 24 alumnes repartits en 6 grups iguals. Quants alumnes hi ha per grup?", "3", "4", "6", "5"],
    ["Si tens 100 € i compres dues coses de 45 € cadascuna, quant et queda?", "10", "15", "5", "0"],
    ["Cada llibre costa 15 €. Quant costen 3 llibres?", "30", "45", "40", "35"],
    ["Tens 2 monedes de 2 € i 3 monedes d’1 €. Quants diners tens?", "7", "6", "8", "5"],
    ["Un tren surt a les 10:00 i arriba a les 13:00. Quantes hores dura el trajecte?", "2", "3", "4", "5"],
    ["Una botiga ven sabates per 60 € i fa un descompte de 15 €. Quant pagues?", "45", "50", "55", "40"],
    ["Tens 5 paquets amb 6 cromos cadascun. Quants cromos tens?", "30", "25", "35", "40"],
    ["Hi ha 40 caramel·les per repartir entre 5 nens. Quants en rep cada nen?", "7", "6", "8", "9"],
    ["En Pere compra 3 quilos de patates a 2 €/kg. Quant paga?", "5", "6", "7", "8"],
    ["Una aula té 6 files de 5 cadires. Quantes cadires hi ha?", "30", "25", "35", "28"],
    ["Si tens 90 € i et regalen 25 €, quant tens en total?", "115", "110", "105", "120"],
    ["Una pilota costa 18 €. Quants pots comprar amb 54 €?", "2", "3", "4", "5"],
    ["Tens 3 llibres amb 20 pàgines cadascun. Quantes pàgines hi ha en total?", "50", "60", "70", "40"],
    ["Si en una caixa hi ha 10 galetes i en menges 3, quantes en queden?", "6", "7", "8", "9"],
    ["Un autobús porta 32 persones. En baixen 14. Quantes en queden?", "16", "18", "20", "22"],
    ["Cada entrada al cinema val 9 €. Quant costen 4 entrades?", "36", "35", "32", "34"],
    ["En una classe hi ha 28 alumnes. Si es divideixen en grups de 7, quants grups hi ha?", "3", "4", "5", "6"],
    ["Un llibre té 120 pàgines. Si en llegeixes 30 al dia, quant tardes?", "3", "4", "5", "6"],
    ["Tens 60 caramels i els poses en bosses de 10. Quantes bosses pots fer?", "5", "6", "7", "8"],
    ["Una botiga ven joguines a 25 €. Quantes pots comprar amb 100 €?", "3", "4", "5", "6"],
    ["Una granja té 8 gallines i cada una pon 2 ous al dia. Quants ous al dia es pon?", "16", "14", "12", "18"]
]

ResCorMat = [
    "7", "7", "20", "18", "15", "20", "40", "36", "12", "4",
    "10", "45", "7", "3", "45", "30", "8", "6", "30", "115",
    "3", "60", "7", "18", "36", "4", "4", "6", "4", "16"
]



# Taula pregunta respostes Cultura General
PreResGen = [
    ["Quin és el riu més llarg del món?", "Nil", "Amazones", "Yangtzé", "Mississipí"],
    ["En quin país es troba la Torre Eiffel?", "Espanya", "Itàlia", "França", "Alemanya"],
    ["Qui va pintar la Mona Lisa?", "Van Gogh", "Dalí", "Picasso", "Leonardo da Vinci"],
    ["En quin continent està Egipte?", "Àsia", "Àfrica", "Europa", "Amèrica"],
    ["Quina és la capital d'Alemanya?", "Berlín", "Munic", "Hamburg", "Frankfurt"],
    ["Quants planetes té el sistema solar?", "7", "8", "9", "10"],
    ["Quin és el metall més utilitzat al món?", "Or", "Alumini", "Ferro", "Coure"],
    ["Quin és l’animal més gran del món?", "Elefant", "Balena blava", "Girafa", "Rinoceront"],
    ["Quin és l’idioma més parlat al món?", "Anglès", "Castellà", "Xinès mandarí", "Àrab"],
    ["En quin país es troba el Machu Picchu?", "Brasil", "Xile", "Perú", "Mèxic"],
    ["Quina és la moneda del Regne Unit?", "Euro", "Dòlar", "Lliura esterlina", "Corona"],
    ["Qui va escriure 'Romeu i Julieta'?", "Shakespeare", "Cervantes", "Goethe", "Tolstoi"],
    ["Quin és l’oceà més gran?", "Atlàntic", "Pacífic", "Índic", "Àrtic"],
    ["Quina és la capital del Japó?", "Pekín", "Kyoto", "Osaka", "Tòquio"],
    ["Quin país té més habitants?", "Índia", "Estats Units", "Xina", "Indonèsia"],
    ["Quin és el continent més petit?", "Europa", "Antàrtida", "Oceania", "Àsia"],
    ["Quin esport juga Messi?", "Tennis", "Futbol", "Bàsquet", "Handbol"],
    ["Quin és el símbol químic de l’aigua?", "H2O", "O2", "HO2", "H2O2"],
    ["Com es diu el satèl·lit natural de la Terra?", "Lluna", "Sol", "Estel", "Plutó"],
    ["Quina ciutat espanyola és coneguda per l’Alhambra?", "Madrid", "Barcelona", "Granada", "Sevilla"],
    ["Quin és el país amb més illes?", "Indonèsia", "Canadà", "Suècia", "Filipines"],
    ["Quin instrument té tecles blanques i negres?", "Guitarra", "Violí", "Piano", "Trompeta"],
    ["Com es diu la ciència que estudia els estels?", "Geologia", "Biologia", "Astronomia", "Meteorologia"],
    ["Quin és el pintor de 'La nit estelada'?", "Monet", "Picasso", "Van Gogh", "Rembrandt"],
    ["Quina llengua es parla a Brasil?", "Espanyol", "Portuguès", "Francès", "Anglès"],
    ["Com es diu la capital de Catalunya?", "Madrid", "Barcelona", "València", "Girona"],
    ["Quin és l’animal més ràpid a la terra?", "Guepard", "Tigre", "Cavall", "Lleopard"],
    ["Quina és la muntanya més alta del món?", "Everest", "K2", "Montblanc", "Annapurna"],
    ["Quin inventor va descobrir la bombeta?", "Newton", "Tesla", "Edison", "Galileu"],
    ["Com es diu el planeta vermell?", "Saturn", "Venus", "Mart", "Júpiter"],
]

# Taula de respostes correctes Cultura General
ResCorGen = [
    "Nil",
    "França",
    "Leonardo da Vinci",
    "Àfrica",
    "Berlín",
    "8",
    "Ferro",
    "Balena blava",
    "Xinès mandarí",
    "Perú",
    "Lliura esterlina",
    "Shakespeare",
    "Pacífic",
    "Tòquio",
    "Xina",
    "Oceania",
    "Futbol",
    "H2O",
    "Lluna",
    "Granada",
    "Suècia",
    "Piano",
    "Astronomia",
    "Van Gogh",
    "Portuguès",
    "Barcelona",
    "Guepard",
    "Everest",
    "Edison",
    "Mart",
]

# Taula pregunta respostes Història
PreResHist = [
    ["Qui va ser el primer emperador romà?", "Juli Cèsar", "August", "Neró", "Marc Antoni"],
    ["En quin any va caure l’Imperi Romà d’Occident?", "410", "476", "500", "455"],
    ["Qui va descobrir Amèrica el 1492?", "Vasco da Gama", "Cristòfor Colom", "Magallanes", "Vasco Núñez"],
    ["Quin esdeveniment va començar el 14 de juliol de 1789?", "Revolució Americana", "Revolució Francesa", "Primera Guerra Mundial", "Segona Guerra Mundial"],
    ["Qui va ser reina d’Anglaterra durant l’Edat Mitjana?", "Isabel I", "Victòria", "Elisabet II", "Matilde de Cançó"],
    ["En quin any va començar la I Guerra Mundial?", "1914", "1939", "1920", "1918"],
    ["Qui era líder del partit feixista a Itàlia?", "Hitler", "Mussolini", "Stalin", "Franco"],
    ["Quin imperi va construir Angkor Wat?", "Maià", "Khmer", "Inca", "Aztec"],
    ["Quan va caure el Mur de Berlín?", "1989", "1979", "1991", "1985"],
    ["Qui va liderar la revolució cubana?", "Fidel Castro", "Che Guevara", "Raúl Castro", "Hugo Chávez"],
    ["En quin any va independitzar-se l’Índia del Regne Unit?", "1947", "1950", "1935", "1960"],
    ["Qui va escriure 'El Manifest Comunista'?", "Lenin", "Marx i Engels", "Trotski", "Stalin"],
    ["Quin país va bombardejar Hiroshima el 1945?", "Alemanya", "Japó", "Estats Units", "Unió Soviètica"],
    ["Qui va ser la primera dona en volar sola a través de l’Atlàntic?", "Amelia Earhart", "Valentina Tereshkova", "Sally Ride", "Jacqueline Cochran"],
    ["En quin any va caure Constantinoble?", "1453", "1492", "1325", "1517"],
    ["Qui va ser el líder de l’Alemanya nazi?", "Hitler", "Goebbels", "Stalin", "Churchill"],
    ["Quan va acabar la Guerra de Secessió dels EUA?", "1865", "1848", "1901", "1910"],
    ["Qui va ser George Washington?", "Primer president dels EUA", "General romà", "Astronauta", "Filòsof grec"],
    ["Quin explorador va donar el seu nom a l’estret entre Europa i Àsia?", "Magallanes", "Colom", "Bering", "Cook"],
    ["Quan va començar la Revolució Industrial?", "Segle XVIII", "Segle XVII", "Segle XIX", "Segle XX"],
    ["Què va ser l’Imperi Otomà?", "Imperi africà", "Imperi europeu", "Imperi asiàtic", "Imperi africà i europeu"],
    ["Qui va signar l’armistici de la Primera Guerra Mundial?", "Winston Churchill", "Franz Ferdinand", "Generals aliats i alemanys", "Hitler"],
    ["Quin país va ser separat després de la guerra civil de 1949 (Xina)?", "Taiwan", "Mongòlia", "Corea del Nord", "Corea del Sud"],
    ["Qui va idear la democràcia a l’antiga Grècia?", "Plató", "Sòcrates", "Clístenes", "Aristòtil"],
    ["En quin any va esclatar la Revolució Russa?", "1917", "1905", "1922", "1933"],
    ["Què va començar el 1936 a Espanya?", "Guerra Civil", "Dictadura de Franco", "Monarquia", "Segona República"],
    ["Quina ciutat va ser el centre de l’Imperi Bizantí?", "Roma", "Constantinoble", "Atenes", "Jerusalem"],
    ["Qui va escriure 'Les Mil i Una Nits'?", "Anonim", "Shahrazad", "Goethe", "Shakespeare"],
    ["Quan va ser la caiguda de l’Imperi Mongol?", "XIII segle", "XV segle", "XIV segle", "XII segle"],
    ["Quin tractat va acabar la Guerra dels Trenta Anys (1648)?", "Pau de Versalles", "Tractat de Westfàlia", "Tractat de Viena", "Pau d’Utrecht"],
]

ResCorHist = [
    "August",
    "476",
    "Cristòfor Colom",
    "Revolució Francesa",
    "Matilde de Cançó",
    "1914",
    "Mussolini",
    "Khmer",
    "1989",
    "Fidel Castro",
    "1947",
    "Marx i Engels",
    "Estats Units",
    "Amelia Earhart",
    "1453",
    "Hitler",
    "1865",
    "Primer president dels EUA",
    "Bering",
    "Segle XVIII",
    "Imperi europeu",
    "Generals aliats i alemanys",
    "Taiwan",
    "Clístenes",
    "1917",
    "Guerra Civil",
    "Constantinoble",
    "Shahrazad",
    "XIV segle",
    "Tractat de Westfàlia",
]

# Taula pregunta respostes Geografia
PreResGeo = [
    ["Quina és la capital d’Alemanya?", "Munic", "Hamburg", "Frankfurt", "Berlín"],
    ["Quin país té la ciutat de Sydney?", "Nou Zelanda", "Austràlia", "Canadà", "Sud-àfrica"],
    ["Quin és el continent més gran?", "Àfrica", "Àsia", "Europa", "Amèrica del Sud"],
    ["Quin oceà és el més profund?", "Atlàntic", "Índic", "Pacífic", "Àrtic"],
    ["Quina és la muntanya més alta d’Àfrica?", "Kenya", "Kilimanjaro", "Montserrat", "Atlas"],
    ["Quina és la capital del Brasil?", "Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
    ["Quin riu travessa París?", "Rin", "Danubi", "Tàmesi", "Sena"],
    ["Quin país té la major població?", "Índia", "Xina", "Estats Units", "Indonèsia"],
    ["Quina és la capital de Japó?", "Osaka", "Tokio", "Tòquio", "Kioto"],
    ["Quants oceans hi ha al món?", "4", "5", "6", "7"],
    ["Quina és la península més gran del món?", "Aràbiga", "Ibèrica", "Indo-xinesa", "Escandinava"],
    ["Quina ciutat es diu 'ciutat eterna'?", "Roma", "Atenes", "Jerusalem", "París"],
    ["On es troba la Gran Muralla Xinesa?", "Xina", "Japó", "Mongòlia", "Corea"],
    ["Quina és la capital d’Egipte?", "El Caire", "Alexandria", "Luxor", "Gizeh"],
    ["Quina és la capital de Sud-àfrica?", "Johannesburg", "Pretòria", "Ciutat del Cap", "Durban"],
    ["Quin país està entre França i Espanya?", "Itàlia", "Andorra", "Portugal", "Bèlgica"],
    ["Quin mar limita amb la Costa Brava?", "Mar Mediterrani", "Mar Cantàbric", "Mar Egeu", "Mar Roig"],
    ["Quina és la capital de Mèxic?", "Guadalajara", "Monterrey", "Ciudad de Mèxic", "Cancún"],
    ["Quin país té la forma d’un triangle invertit (Índia)?", "Índia", "Bangladesh", "Pakistan", "Nepal"],
    ["Quina és la capital de Turquia?", "Istanbul", "Ankara", "Esmirna", "Antalya"],
    ["Quants estats té Estats Units?", "50", "51", "49", "52"],
    ["Quina és la muntanya més alta del món?", "K2", "Everest", "Kanchenjunga", "Lhotse"],
    ["Quina és la capital d’Itàlia?", "Milà", "Roma", "Venècia", "Florència"],
    ["En quin oceà es troba Madagascar?", "Atlàntic", "Índic", "Pacífic", "Àrtic"],
    ["Quina és la capital de Rússia?", "Sant Petersburg", "Moscou", "Novosibirsk", "Kazan"],
    ["Quin país té capitals separades (llegislativa i administrativa)?", "Sud-àfrica", "Estats Units", "Brasil", "Xina"],
    ["Quina és la capital de Corea del Sud?", "Seül", "Busan", "Incheon", "Daegu"],
    ["Quin mar banya la costa de Galícia?", "Atlàntic", "Cantàbric", "Mediterrani", "Roig"],
    ["Quin país té el desert del Gobi?", "Xina", "Índia", "Mongòlia", "Pakistan"],
    ["Quina és la capital d’Argentina?", "Còrdova", "Rosario", "Buenos Aires", "Mendoza"],
    ["Quin país té la forma d’un bota?", "Itàlia", "Grècia", "Espanya", "Portugal"],
    ["Quina és la ciutat més poblada del món?", "Tokio", "Delhi", "Xangai", "São Paulo"],
]

ResCorGeo = [
    "Berlín",
    "Austràlia",
    "Àsia",
    "Pacífic",
    "Kilimanjaro",
    "Brasília",
    "Sena",
    "Xina",
    "Tòquio",
    "5",
    "Aràbiga",
    "Roma",
    "Xina",
    "Pretòria",
    "Andorra",
    "Mar Mediterrani",
    "Ciudad de Mèxic",
    "Índia",
    "Ankara",
    "50",
    "Everest",
    "Roma",
    "Índic",
    "Moscou",
    "Sud-àfrica",
    "Seül",
    "Atlàntic",
    "Mongòlia",
    "Buenos Aires",
    "Itàlia",
    "Tokio",
]

# Taula pregunta respostes Tecnologia
PreResTec = [
    ["Què significa CPU?", "Central Power Unit", "Central Processing Unit", "Computer Performance Unit", "Central Program Unit"],
    ["Què és la RAM?", "Memòria permanent", "Memòria de treball", "Dispositiu de xarxa", "Targeta gràfica"],
    ["Què fa el sistema operatiu Windows?", "Crea vídeos", "Gestiona recursos del PC", "Dissenya webs", "Imprimeix"],
    ["Què és una IP?", "Adreça d’internet", "Impressora personal", "Programació instantània", "Interfície pública"],
    ["Què és el Wi‑Fi?", "Emissió de ràdio", "Connexió inalàmbrica", "Dispositiu d’emmagatzematge", "Tipus de virus"],
    ["Què és 'cloud computing'?", "Emmagatzematge local", "Servei en el núvol", "Sistema operatiu", "Maquinari físic"],
    ["Què fa un antivirus?", "Copia arxius", "Protegeix de programari maliciós", "Augmenta memòria", "Millora processador"],
    ["Què significa USB?", "Universal Serial Bus", "Universal Software Bus", "Unique Serial Bus", "Universal System Backup"],
    ["Què és HTML?", "Llenguatge de programació", "Llenguatge de marcat", "Base de dades", "Sistema operatiu"],
    ["Per a què serveix un navegador?", "Emmagatzemar dades", "Mostrar pàgines web", "Edita imatges", "Envia correu"],
    ["Què és la GPU?", "Processador gràfic", "Memòria ràpida", "Dispositiu d’àudio", "Sensor"],
    ["Què és un SSD?", "Disc dur mecànic", "Disc dur d’estat sòlid", "Targeta de xarxa", "Font d’alimentació"],
    ["Què és HTML5?", "Nova versió de HTML", "Servei web", "Llenguatge de programació", "Sistema operatiu"],
    ["Què significa 'AI'?", "Artificial Intelligence", "Automated Interface", "Audio Input", "Advanced Internet"],
    ["Què és l’IOT?", "Internet of Things", "Integration of Technology", "International Organization of Telecom", "Interface of Things"],
    ["Què és un firewall?", "Tallafocs", "Programa de seguretat", "Virus informàtic", "Maquinari d’àudio"],
    ["Per a què serveix 'Bluetooth'?", "Connexió per cable", "Connexió inalàmbrica curta distància", "Adreça IP", "Sistema operatiu"],
    ["Què és una URL?", "Adreça web", "Llenguatge de marcat", "Base de dades", "Sistema operatiu"],
    ["Què és el HTML?", "Llenguatge de marcat", "Sistema operatiu", "Programari maliciós", "Base de dades"],
    ["Què fa el protocol HTTPS?", "Descarrega fitxers", "Xifrat la connexió web", "Imprimeix pàgines", "Controla el maquinari"],
    ["Què és el blockchain?", "Tipus de xarxa social", "Registre distribuït", "Sistema operatiu", "Dispositiu de memòria"],
    ["Què és la realitat virtual?", "Video real", "Entorn generat per ordinador", "Còpia de seguretat", "Tipus de programari"],
    ["Què és el 5G?", "Assistència virtual", "Tecnologia de xarxa mòbil", "Servei de streaming", "Tipus de malware"],
    ["Què és Linux?", "Sistema operatiu", "Llenguatge de programació", "Navegador web", "Aplicació"],
    ["Què és Python?", "Base de dades", "Llenguatge de programació", "Sistema operatiu", "Xarxa social"],
    ["Què és un drone?", "Robot volador", "Aplicació d’ordinador", "Programari maliciós", "Tipus de cable"],
    ["Què és el USB-C?", "Versió antiga d’USB", "Nova connexió universal", "Sistema operatiu", "Programari"],
    ["Què és la intel·ligència artificial generativa?", "Crear art intel·lectual", "Models que generen contingut", "Virus informàtic", "Xarxa social"],
    ["Què és l’e-commerce?", "Venda en línia", "Disc local", "Sistema operatiu", "Tipus de programari"],
]

ResCorTec = [
    "Central Processing Unit",
    "Memòria de treball",
    "Gestiona recursos del PC",
    "Adreça d’internet",
    "Connexió inalàmbrica",
    "Servei en el núvol",
    "Protegeix de programari maliciós",
    "Universal Serial Bus",
    "Llenguatge de marcat",
    "Mostrar pàgines web",
    "Processador gràfic",
    "Disc dur d’estat sòlid",
    "Nova versió de HTML",
    "Artificial Intelligence",
    "Internet of Things",
    "Programa de seguretat",
    "Connexió inalàmbrica curta distància",
    "Adreça web",
    "Llenguatge de marcat",
    "Xifrat la connexió web",
    "Registre distribuït",
    "Entorn generat per ordinador",
    "Tecnologia de xarxa mòbil",
    "Sistema operatiu",
    "Llenguatge de programació",
    "Robot volador",
    "Nova connexió universal",
    "Models que generen contingut",
    "Venda en línia",
]

PreResCie = [
    ["Quin òrgan bombeja la sang?", "Cervell", "Pulmons", "Cor", "Fetge"],
    ["Quin element químic té el símbol H?", "Heli", "Hidrogen", "Hafni", "Holmi"],
    ["Quin és el planeta més proper al Sol?", "Venus", "Terra", "Mercuri", "Mart"],
    ["Què són els glòbuls vermells?", "Cèl·lules nervioses", "Cèl·lules immunitàries", "Cèl·lules sanguínies que transporten oxigen", "Virus"],
    ["Quin gas respirem principalment?", "Diòxid de carboni", "Hidrogen", "Oxigen", "Nitrogen"],
    ["Quin és el sistema responsable del moviment?", "Digestiu", "Circulatori", "Muscular", "Nerviós"],
    ["Quin és el satèl·lit natural de la Terra?", "Sol", "Marte", "Luna", "Europa"],
    ["Quina part de la planta fa la fotosíntesi?", "Arrel", "Tija", "Fulla", "Flor"],
    ["Què és una espècie?", "Tipus de roca", "Tipus d’àtom", "Grup d’éssers vius amb característiques comunes", "Zona geogràfica"],
    ["Què és l’ADN?", "Àcid desoxiribonucleic", "Àcid làctic", "Glucosa", "Proteïna sanguínia"],
    ["Quin planeta té anells visibles?", "Terra", "Marte", "Saturn", "Venus"],
    ["Com es diu el procés de pas de sòlid a líquid?", "Condensació", "Sublimació", "Fusió", "Evaporació"],
    ["Quants ossos té un adult?", "206", "305", "100", "150"],
    ["Quin és el principal òrgan del sistema nerviós?", "Cor", "Estómac", "Cervell", "Ronyó"],
    ["Què mesura un termòmetre?", "Pressió", "Hidratació", "Temperatura", "Velocitat"],
    ["Quin òrgan elimina l’orina?", "Pulmons", "Ronyons", "Estómac", "Fetge"],
    ["Quina és la unitat de mesura de la força?", "Pascal", "Newton", "Joule", "Volt"],
    ["Què és un herbívor?", "Menja carn", "Menja plantes", "Menja de tot", "No menja"],
    ["Quina vitamina s’obté del Sol?", "Vitamina A", "Vitamina B", "Vitamina C", "Vitamina D"],
    ["Què són els bacteris?", "Animals petits", "Virus", "Microorganismes", "Plantes"],
    ["Què regula la gravetat?", "Moviment de l’aire", "Caiguda dels cossos", "Electricitat", "Llum"],
    ["Què és una metamorfosi?", "Canvi químic", "Transformació d’un animal", "Evaporació", "Digestió"],
    ["Què mesura un baròmetre?", "Temperatura", "Humitat", "Pressió atmosfèrica", "Llum"],
    ["Quin tipus de dents serveixen per tallar?", "Canins", "Incisius", "Molars", "Premolars"],
    ["Quin és el principal component de l’aigua?", "Hidrogen i oxigen", "Carboni i oxigen", "Hidrogen i nitrogen", "Oxigen i heli"],
    ["Què fan els pulmons?", "Filtren sang", "Digereixen", "Absorbeixen nutrients", "Intercanvien gasos"],
    ["Com es diu el procés de respiració de les plantes?", "Fotosíntesi", "Transpiració", "Respiració cel·lular", "Condensació"],
    ["Quina funció fa el sistema digestiu?", "Oxigenar la sang", "Produir hormones", "Descompondre aliments", "Transportar oxigen"],
    ["Quin és l’estat del vapor d’aigua?", "Sòlid", "Líquid", "Gasós", "Plasma"],
    ["Quin tipus de planeta és la Terra?", "Gasós", "Nan", "Rocós", "Líquid"],
]

ResCorCie = [
    "Cor", "Hidrogen", "Mercuri", "Cèl·lules sanguínies que transporten oxigen", "Nitrogen", "Muscular", "Luna", "Fulla", "Grup d’éssers vius amb característiques comunes", "Àcid desoxiribonucleic",
    "Saturn", "Fusió", "206", "Cervell", "Temperatura", "Ronyons", "Newton", "Menja plantes", "Vitamina D", "Microorganismes", "Caiguda dels cossos", "Transformació d’un animal", "Pressió atmosfèrica",
    "Incisius", "Hidrogen i oxigen", "Intercanvien gasos", "Respiració cel·lular", "Descompondre aliments", "Gasós", "Rocós"
]

PreResEsport = [
    ["Quants jugadors té un equip de futbol?", "10", "11", "12", "9"],
    ["Quina disciplina forma part dels Jocs Olímpics?", "Pòquer", "Futbol", "Bàsquet", "Escacs"],
    ["Quin és el principal objectiu del ioga?", "Córrer ràpid", "Relaxació i força", "Ganar múscul", "Competir"],
    ["En quin esport es fa servir una raqueta?", "Hoquei", "Tennis", "Futbol", "Rem"],
    ["Quants minuts dura un partit de futbol (temps regular)?", "60", "70", "90", "120"],
    ["Com es diu el moviment bàsic per nedar d’esquena?", "Papallona", "Crol", "Braça", "Esquena"],
    ["Quants jugadors hi ha en bàsquet per equip al camp?", "5", "6", "7", "4"],
    ["Què és el dopatge?", "Entrenament", "Suport", "Consum de substàncies il·legals", "Reforç mental"],
    ["Qui va guanyar més medalles olímpiques?", "Usain Bolt", "Michael Phelps", "Nadal", "Simone Biles"],
    ["En quin esport s'utilitza una pista de 400 m?", "Tennis", "Futbol", "Atletisme", "Natació"],
    ["En quin esport s'utilitza un tatami?", "Boxa", "Judo", "Rugbi", "Futbol sala"],
    ["Què és el fair play?", "Empènyer el rival", "Fer trampes", "Joc net", "Celebrar massa"],
    ["Què treballa la flexibilitat?", "Força", "Resistència", "Mobilitat articular", "Velocitat"],
    ["Quina part del cos impulsa la carrera?", "Peus", "Cames", "Braços", "Coll"],
    ["Quin esport es juga sobre gel?", "Esquí aquàtic", "Patinatge artístic", "Voleibol", "Handbol"],
    ["Quin és l'esport que es juga amb una cistella?", "Futbol", "Bàsquet", "Rugbi", "Hoquei"],
    ["Què mesura el cronòmetre?", "Distància", "Temps", "Alçada", "Força"],
    ["Quin esport es practica amb una bicicleta?", "Ciclisme", "Esgrima", "Rem", "Judo"],
    ["Com es diu el salt sense córrer?", "Salt vertical", "Salt de llargada", "Salt d’alçada", "Salt de potència"],
    ["Quin tipus d’esport és la marató?", "Força", "Velocitat", "Fons", "Salt"],
    ["Què és la coordinació?", "Sincronitzar moviments", "Córrer ràpid", "Fer salts", "Aixecar pes"],
    ["Quin esport inclou disciplines com espasa i sabre?", "Esgrima", "Rem", "Atletisme", "Lluita"],
    ["Quants segons tens per servir en tennis?", "15", "25", "10", "5"],
    ["Què és un estirament?", "Moviment violent", "Recolzament", "Acció per millorar flexibilitat", "Carrera ràpida"],
    ["Quin esport es juga amb una pilota ovalada?", "Bàsquet", "Rugbi", "Futbol sala", "Tennis"],
    ["Quin esport es practica amb cavalls?", "Jòquei", "Equitació", "Ciclisme", "Esgrima"],
    ["Què és el fons físic?", "Poc esforç", "Resistència llarga", "Velocitat màxima", "Potència curta"],
    ["En quin esport es fa servir un casc i una bici?", "Esgrima", "Hípica", "Ciclisme", "Rugbi"],
    ["Quin esport es juga amb pals i porteries sobre gel?", "Hòquei sobre gel", "Hoquei herba", "Bàsquet", "Esgrima"],
    ["Quin esport és olímpic d’estiu?", "Snowboard", "Esgrima", "Esquí", "Trineu"],
]

ResCorEsport = [
    "11", "Futbol", "Relaxació i força", "Tennis", "90", "Esquena", "5", "Consum de substàncies il·legals", "Michael Phelps", "Atletisme",
    "Judo", "Joc net", "Mobilitat articular", "Cames", "Patinatge artístic", "Bàsquet", "Temps", "Ciclisme", "Salt vertical", "Fons",
    "Sincronitzar moviments", "Esgrima", "25", "Acció per millorar flexibilitat", "Rugbi", "Equitació", "Resistència llarga", "Ciclisme", "Hòquei sobre gel", "Esgrima"
]


PreResArts = [
    ["Quantes cordes té una guitarra espanyola?", "4", "5", "6", "7"],
    ["Qui va pintar La Mona Lisa?", "Picasso", "Van Gogh", "Leonardo da Vinci", "Dalí"],
    ["Quin instrument té tecles?", "Guitarra", "Piano", "Violí", "Trompeta"],
    ["Què és una simfonia?", "Cançó", "Obra musical llarga per orquestra", "Ball", "Pintura"],
    ["Quin pintor és famós pel cubisme?", "Miró", "Picasso", "Goya", "Van Gogh"],
    ["Com es diu l’art de plegar paper?", "Origami", "Mandala", "Stencil", "Collage"],
    ["Quants colors primaris hi ha?", "2", "3", "4", "5"],
    ["Qui va compondre la 5a simfonia?", "Beethoven", "Mozart", "Bach", "Vivaldi"],
    ["Què és una aquarel·la?", "Pintura amb oli", "Pintura amb aigua", "Dibuix amb llapis", "Collage"],
    ["Quin estil de ball prové dels EUA?", "Flamenc", "Hip-hop", "Sardana", "Tango"],
    ["Quin instrument té baquetes?", "Violí", "Timbal", "Trompeta", "Flauta"],
    ["Què és una òpera?", "Concert de rock", "Obra musical amb cantants", "Simfonia curta", "Teatre sense música"],
    ["Quin compositor és conegut per 'Les Quatre Estacions'?", "Bach", "Mozart", "Vivaldi", "Beethoven"],
    ["Quin gènere és el jazz?", "Clàssic", "Modern", "Improvisat", "Tradicional"],
    ["Com es diu el conjunt d’actors d’una obra?", "Grup", "Cor", "Companyia", "Taller"],
    ["Quina dansa és típica de Catalunya?", "Tango", "Flamenc", "Sardana", "Sevillana"],
    ["Quin pintor tenia una etapa blava?", "Miró", "Dalí", "Picasso", "Monet"],
    ["Quin instrument és de vent?", "Piano", "Flauta", "Violí", "Arpa"],
    ["Què són les arts escèniques?", "Cinema", "Teatre, dansa i música en viu", "Pintura", "Escultura"],
    ["Què és un mural?", "Quadre petit", "Pintura sobre paret", "Escultura de fusta", "Fotografia"],
    ["Qui va pintar 'El crit'?", "Munch", "Goya", "Renoir", "Degas"],
    ["Quin element és bàsic per dibuixar?", "Llum", "Sorra", "Llapis", "Fusta"],
    ["Què és un pentagrama?", "Instrument", "Sistema de 5 línies per escriure música", "Nota musical", "Ritme"],
    ["Què és el tempo?", "Altura del so", "Velocitat de la música", "Tipus d’instrument", "Color musical"],
    ["Quin compositor era sord?", "Mozart", "Bach", "Beethoven", "Vivaldi"],
    ["Quin tipus de música és per ballar?", "Rock", "Pop", "Discoteca", "Totes les anteriors"],
    ["Què fa un director d’orquestra?", "Ballar", "Compondre", "Guiar els músics", "Afinar"],
    ["Què és una escultura?", "Música", "Forma artística tridimensional", "Ball", "Dibuix en paper"],
    ["Quina és la funció d’un museu?", "Ballar", "Exposar art", "Cantar", "Vendre"],
    ["Què és una partitura?", "Dibuix", "Text", "Esquema de música escrita", "Cançó"],
]

ResCorArts = [
    "6", "Leonardo da Vinci", "Piano", "Obra musical llarga per orquestra", "Picasso", "Origami", "3", "Beethoven", "Pintura amb aigua", "Hip-hop",
    "Timbal", "Obra musical amb cantants", "Vivaldi", "Improvisat", "Companyia", "Sardana", "Picasso", "Flauta", "Teatre, dansa i música en viu", "Pintura sobre paret",
    "Munch", "Llapis", "Sistema de 5 línies per escriure música", "Velocitat de la música", "Beethoven", "Totes les anteriors", "Guiar els músics", "Forma artística tridimensional", "Exposar art", "Esquema de música escrita"
]

