PreResProg = [
    ["Quin llenguatge s’utilitza principalment per crear pàgines web?", "Python", "HTML", "Java", "C++"],
    ["Què fa la funció print() en Python?", "Llegeix dades", "Imprimeix valors per pantalla", "Guarda en un fitxer", "Calcula la mitjana"],
    ["Quin d’aquests és un tipus de dada en JavaScript?", "decimal", "char", "float", "string"],
    ["Com s’indica un comentari d’una línia en Python?", "//", "#", "/* */", "--"],
    ["Com pots declarar una variable en JavaScript?", "int x = 5;", "let x = 5;", "var: x = 5", "declare x = 5"],
    ["Quin símbol s’utilitza per a la igualtat en una comparació en Python?", "=", "==", "!=", "==="],
    ["Quin resultat dona: 3 + '3' en JavaScript?", "6", "Error", "33", "undefined"],
    ["Quin bucle repeteix mentre una condició sigui certa?", "for", "if", "while", "switch"],
    ["Quin llenguatge és famós per a l’anàlisi de dades?", "C#", "Ruby", "Python", "Swift"],
    ["Què retorna una funció sense cap return en Python?", "None", "True", "0", "Error"],
    ["Com es defineix una funció en Python?", "function nom()", "func nom()", "def nom():", "fun nom()"],
    ["Quina estructura s’utilitza per triar entre múltiples opcions?", "loop", "array", "switch", "class"],
    ["Com s’escriu una llista en Python?", "{1,2,3}", "[1,2,3]", "(1,2,3)", "<1,2,3>"],
    ["Quin mètode afegeix un element a una llista en Python?", "add()", "append()", "push()", "insert()"],
    ["Quina extensió té un fitxer Python?", ".java", ".html", ".py", ".js"],
    ["Què és una variable booleana?", "Una variable que conté decimals", "Una variable amb text", "Una variable amb True o False", "Una funció"],
    ["Quin d’aquests és un operador lògic?", "+", "=", "and", "%"],
    ["Per què s’utilitza CSS?", "Crear aplicacions", "Donar estil a pàgines web", "Fer càlculs", "Desar dades"],
    ["Com es pot repetir codi 10 vegades en Python?", "while x < 10", "for i in range(10)", "if x < 10", "loop(10)"],
    ["Quin d’aquests llenguatges NO és de programació?", "Python", "HTML", "C++", "Java"],
]
ResCorProg = [
    "HTML",
    "Imprimeix valors per pantalla",
    "string",
    "#",
    "let x = 5;",
    "==",
    "33",
    "while",
    "Python",
    "None",
    "def nom():",
    "switch",
    "[1,2,3]",
    "append()",
    ".py",
    "Una variable amb True o False",
    "and",
    "Donar estil a pàgines web",
    "for i in range(10)",
    "HTML",
]

# Taula pregunta respostes
PreResMat = [
    ["Una entrada general per un concert costa 15 €, i una entrada VIP costa 25 €. Si s’han venut 4 entrades generals i 2 VIP, quin ha estat l’import total recaptat?", "110 €", "100 €", "120 €", "90 €"],
    ["En Joan té 12 anys més que en Pere. Si la suma de les seves edats és 40, quants anys tenen en Joan i en Pere?", "Joan: 20, Pere: 20", "Joan: 26, Pere: 14", "Joan: 24, Pere: 16", "Joan: 28, Pere: 12"],
    ["La Maria compra pomes a 2 € cadascuna. Si es gasta 18 €, quantes pomes ha comprat?", "8 pomes", "10 pomes", "6 pomes", "9 pomes"],
    ["Un nombre sumat amb 7 dóna 21. Quin és aquest nombre?", "12", "16", "14", "13"],
    ["Una entrada de cinema costa 8 €, i unes crispetes costen 5 €. Si en total s'han gastat 39 € en entrades i crispetes, i s'han comprat 3 entrades, quantes bossetes de crispetes s'han comprat?", "4 bossetes", "3 bossetes", "2 bossetes", "5 bossetes"],
    ["La Carla té el doble de diners que en Marc. Si entre tots dos tenen 72 €, quant té cadascú?", "Carla: 36, Marc: 36", "Carla: 30, Marc: 42", "Carla: 48, Marc: 24", "Carla: 40, Marc: 32"],
    ["Si a un nombre li multipliquem per 4 i li restem 6, obtenim 18. Quin és aquest nombre?", "5", "7", "4", "6"],
    ["Si la meitat d’un nombre menys 3 és igual a 7, quin és el nombre?", "14", "20", "24", "16"],
    ["Una botiga ven llapis a 1 € i bolígrafs a 2 €. Si una persona compra 10 objectes per un total de 15 €, quants llapis i bolígrafs ha comprat?", "5 llapis i 5 bolígrafs", "6 llapis i 4 bolígrafs", "4 llapis i 6 bolígrafs", "3 llapis i 7 bolígrafs"],
    ["En un examen, la puntuació s’obté segons la fórmula 2(x+3)=182(x+3)=18, on x és el nombre de respostes correctes. Quantes respostes correctes ha tingut?", "9", "5", "6", "7"],
    ["Un nombre més 5 dona 12. Quin és el nombre?", "5", "6", "7", "8"],
    ["El doble d’un nombre és 18. Quin és el nombre?", "10", "8", "9", "12"],
    ["Si restes 4 a un nombre, obtens 9. Quin és el nombre?", "11", "13", "12", "10"],
    ["Un nombre dividit entre 3 dona 7. Quin és el nombre?", "21", "18", "24", "27"],
    ["Tres vegades un nombre és 27. Quin és el nombre?", "8", "9", "10", "11"],
    ["Si sumes 8 a un nombre, obtens 20. Quin és el nombre?", "12", "10", "14", "15"],
    ["Si multipliques un nombre per 5 obtens 45. Quin és el nombre?", "8", "10", "9", "11"],
    ["La meitat d’un nombre és 16. Quin és el nombre?", "30", "34", "32", "36"],
    ["Un nombre menys 6 dona 13. Quin és el nombre?", "17", "18", "19", "20"],
    ["Si restes 9 d’un nombre i obtens 2, quin és el nombre?", "10", "11", "12", "13"],
    ["El triple d’un nombre és 15. Quin és el nombre?", "4", "5", "6", "3"],
    ["Si sumes 3 a un nombre i obtens 18, quin és el nombre?", "13", "14", "15", "16"],
    ["Una entrada costa 7 € i compres 5. Quin és el cost total?", "30", "35", "40", "45"],
    ["En Pau té 3 vegades l’edat de la seva germana. Si ella té 5 anys, quants anys té en Pau?", "10", "12", "15", "18"],
    ["En una botiga, 4 bolígrafs costen 6 €. Quant costa 1 bolígraf?", "2 €", "1,5 €", "1 €", "3 €"],
    ["En Jordi ha fet 5 exercicis més que en Marc. Si en Jordi n’ha fet 17, quants n’ha fet en Marc?", "11", "12", "13", "14"],
    ["Si a un nombre li sumes 4 i després el dobles, obtens 20. Quin és el nombre?", "6", "7", "8", "5"],
    ["Un número dividit per 4 dona 6. Quin és el número?", "20", "22", "24", "26"],
    ["Si restes 7 a un nombre i obtens 10, quin és el nombre?", "15", "16", "17", "18"],
    ["La suma de dos nombres consecutius és 41. Quin és el menor dels dos?", "20", "21", "19", "22"],
]

# Taula de respostes correctes
ResCorMat = [
    "110 €",
    "Joan: 26, Pere: 14",
    "9 pomes",
    "14",
    "3 bossetes",
    "Carla: 48, Marc: 24",
    "6",
    "20",
    "5 llapis i 5 bolígrafs",
    "6",
    "7",
    "9",
    "13",
    "21",
    "9",
    "12",
    "9",
    "32",
    "19",
    "11",
    "5",
    "15",
    "35",
    "15",
    "1,5 €",
    "12",
    "6",
    "24",
    "17",
    "20",
]


# Taula pregunta respostes
PreResGen = [
    ["Quin és el riu més llarg del món?", "Amazones", "Nil", "Danubi", "Mississipí"],
    ["Quin és el país amb més habitants del món?", "Índia", "Estats Units", "Xina", "Indonèsia"],
    ["Qui va pintar la Mona Lisa?", "Dalí", "Picasso", "Van Gogh", "Leonardo da Vinci"],
    ["Quin planeta és més proper al Sol?", "Venus", "Març", "Mercuri", "Terra"],
    ["En quin any va arribar l’home a la Lluna?", "1969", "1971", "1965", "1959"],
    ["Quin és l’idioma més parlat del món?", "Anglès", "Castellà", "Xinès mandarí", "Àrab"],
    ["Qui va escriure *El Quixot*?", "Gabriel García Márquez", "Miguel de Cervantes", "Federico García Lorca", "Lope de Vega"],
    ["Quants continents hi ha?", "5", "6", "7", "8"],
    ["Quina ciutat és la capital d’Austràlia?", "Sydney", "Canberra", "Melbourne", "Perth"],
    ["Com es diu el procés pel qual les plantes fabriquen el seu aliment?", "Fermentació", "Digestió", "Fotosíntesi", "Transpiració"],
    ["Quina és la moneda oficial del Regne Unit?", "Euro", "Lliura", "Dòlar", "Franc"],
    ["En quin oceà es troba Hawaii?", "Atlàntic", "Índic", "Pacífic", "Àrtic"],
    ["Qui va ser el primer president dels Estats Units?", "Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"],
    ["Quin és l'os més gran del cos humà?", "Húmer", "Fèmur", "Tibia", "Crani"],
    ["Quin animal és conegut com el rei de la selva?", "Elefant", "Lleopard", "Lleó", "Tigre"],
    ["Quin és l’element químic amb símbol O?", "Or", "Oxigen", "Osmiridi", "Oli"],
    ["En quin país es troba la Torre Eiffel?", "Itàlia", "Espanya", "França", "Alemanya"],
    ["Quantes tecles té un piano clàssic?", "66", "72", "88", "90"],
    ["Quin país va inventar la pólvora?", "Japó", "Xina", "Grècia", "Índia"],
    ["Quina és la muntanya més alta del món?", "Mont Blanc", "Everest", "Aconcagua", "K2"],
]

# Taula de respostes correctes
ResCorGen = [
    "Nil",
    "Índia",
    "Leonardo da Vinci",
    "Mercuri",
    "1969",
    "Xinès mandarí",
    "Miguel de Cervantes",
    "7",
    "Canberra",
    "Fotosíntesi",
    "Lliura",
    "Pacífic",
    "George Washington",
    "Fèmur",
    "Lleó",
    "Oxigen",
    "França",
    "88",
    "Xina",
    "Everest",
]