PreResHist = [
    ["Qui va ser el primer emperador romà?", "August", "Neró", "Marc Antoni", "Juli Cèsar"],
    ["En quin any va caure l’Imperi Romà d’Occident?", "476", "500", "455", "410"],
    ["Qui va descobrir Amèrica el 1492?", "Cristòfor Colom", "Vasco da Gama", "Magallanes", "Vasco Núñez"],
    ["Quin esdeveniment va començar el 14 de juliol de 1789?", "Revolució Francesa", "Primera Guerra Mundial", "Segona Guerra Mundial", "Revolució Americana"],
    ["Qui va ser reina d’Anglaterra durant l’Edat Mitjana?", "Matilde de Cançó", "Victòria", "Elisabet II", "Isabel I"],
    ["En quin any va començar la I Guerra Mundial?", "1914", "1939", "1918", "1920"],
    ["Qui era líder del partit feixista a Itàlia?", "Mussolini", "Stalin", "Franco", "Hitler"],
    ["Quin imperi va construir Angkor Wat?", "Khmer", "Aztec", "Inca", "Maià"],
    ["Quan va caure el Mur de Berlín?", "1989", "1991", "1985", "1979"],
    ["Qui va liderar la revolució cubana?", "Fidel Castro", "Raúl Castro", "Hugo Chávez", "Che Guevara"],
    ["En quin any va independitzar-se l’Índia del Regne Unit?", "1947", "1960", "1935", "1950"],
    ["Qui va escriure 'El Manifest Comunista'?", "Marx i Engels", "Trotski", "Stalin", "Lenin"],
    ["Quin país va bombardejar Hiroshima el 1945?", "Estats Units", "Japó", "Unió Soviètica", "Alemanya"],
    ["Qui va ser la primera dona en volar sola a través de l’Atlàntic?", "Amelia Earhart", "Sally Ride", "Jacqueline Cochran", "Valentina Tereshkova"],
    ["En quin any va caure Constantinoble?", "1453", "1517", "1325", "1492"],
    ["Qui va ser el líder de l’Alemanya nazi?", "Hitler", "Goebbels", "Churchill", "Stalin"],
    ["Quan va acabar la Guerra de Secessió dels EUA?", "1865", "1910", "1901", "1848"],
    ["Qui va ser George Washington?", "Primer president dels EUA", "Filòsof grec", "Astronauta", "General romà"],
    ["Quin explorador va donar el seu nom a l’estret entre Europa i Àsia?", "Bering", "Cook", "Magallanes", "Colom"],
    ["Quan va començar la Revolució Industrial?", "Segle XVIII", "Segle XX", "Segle XIX", "Segle XVII"],
    ["Què va ser l’Imperi Otomà?", "Imperi europeu", "Imperi africà", "Imperi africà i europeu", "Imperi asiàtic"],
    ["Qui va signar l’armistici de la Primera Guerra Mundial?", "Generals aliats i alemanys", "Franz Ferdinand", "Hitler", "Winston Churchill"],
    ["Quin país va ser separat després de la guerra civil de 1949 (Xina)?", "Taiwan", "Corea del Sud", "Corea del Nord", "Mongòlia"],
    ["Qui va idear la democràcia a l’antiga Grècia?", "Clístenes", "Aristòtil", "Sòcrates", "Plató"],
    ["En quin any va esclatar la Revolució Russa?", "1917", "1933", "1922", "1905"],
    ["Què va començar el 1936 a Espanya?", "Guerra Civil", "Segona República", "Monarquia", "Dictadura de Franco"],
    ["Quina ciutat va ser el centre de l’Imperi Bizantí?", "Constantinoble", "Jerusalem", "Atenes", "Roma"],
    ["Qui va escriure 'Les Mil i Una Nits'?", "Shahrazad", "Goethe", "Shakespeare", "Anonim"],
    ["Quan va ser la caiguda de l’Imperi Mongol?", "XIV segle", "XV segle", "XII segle", "XIII segle"],
    ["Quin tractat va acabar la Guerra dels Trenta Anys (1648)?", "Tractat de Westfàlia", "Tractat de Viena", "Pau d’Utrecht", "Pau de Versalles"],
]

ResCorHist = [
    "August",
    "476",
    "Cristòfor Colom",
    "Revolució Francesa",
    "Matilde de Cançó",
    "1914",
    "Mussolini",
    "Khmer",
    "1989",
    "Fidel Castro",
    "1947",
    "Marx i Engels",
    "Estats Units",
    "Amelia Earhart",
    "1453",
    "Hitler",
    "1865",
    "Primer president dels EUA",
    "Bering",
    "Segle XVIII",
    "Imperi europeu",
    "Generals aliats i alemanys",
    "Taiwan",
    "Clístenes",
    "1917",
    "Guerra Civil",
    "Constantinoble",
    "Shahrazad",
    "XIV segle",
    "Tractat de Westfàlia",
]
