PreResTec = [
    ["Què significa CPU?", "Central Power Unit", "Central Program Unit", "Central Processing Unit", "Computer Performance Unit"],
    ["Què és la RAM?", "Memòria permanent", "Memòria de treball", "Dispositiu de xarxa", "Targeta gràfica"],
    ["Què fa el sistema operatiu Windows?", "Gestiona recursos del PC", "Crea vídeos", "Dissenya webs", "Imprimeix"],
    ["Què és una IP?", "Impressora personal", "Adreça d’internet", "Interfície pública", "Programació instantània"],
    ["Què és el Wi‑Fi?", "Tipus de virus", "Connexió inalàmbrica", "Dispositiu d’emmagatzematge", "Emissió de ràdio"],
    ["Què és 'cloud computing'?", "Sistema operatiu", "Servei en el núvol", "Maquinari físic", "Emmagatzematge local"],
    ["Què fa un antivirus?", "Augmenta memòria", "Protegeix de programari maliciós", "Copia arxius", "Millora processador"],
    ["Què significa USB?", "Universal Serial Bus", "Universal System Backup", "Universal Software Bus", "Unique Serial Bus"],
    ["Què és HTML?", "Llenguatge de marcat", "Sistema operatiu", "Base de dades", "Llenguatge de programació"],
    ["Per a què serveix un navegador?", "Mostrar pàgines web", "Edita imatges", "Emmagatzemar dades", "Envia correu"],
    ["Què és la GPU?", "Processador gràfic", "Memòria ràpida", "Dispositiu d’àudio", "Sensor"],
    ["Què és un SSD?", "Disc dur mecànic", "Disc dur d’estat sòlid", "Font d’alimentació", "Targeta de xarxa"],
    ["Què és HTML5?", "Nova versió de HTML", "Servei web", "Llenguatge de programació", "Sistema operatiu"],
    ["Què significa 'AI'?", "Artificial Intelligence", "Audio Input", "Advanced Internet", "Automated Interface"],
    ["Què és l’IOT?", "Internet of Things", "Integration of Technology", "International Organization of Telecom", "Interface of Things"],
    ["Què és un firewall?", "Programa de seguretat", "Tallafocs", "Maquinari d’àudio", "Virus informàtic"],
    ["Per a què serveix 'Bluetooth'?", "Connexió inalàmbrica curta distància", "Adreça IP", "Connexió per cable", "Sistema operatiu"],
    ["Què és una URL?", "Adreça web", "Sistema operatiu", "Llenguatge de marcat", "Base de dades"],
    ["Què és el HTML?", "Llenguatge de marcat", "Sistema operatiu", "Programari maliciós", "Base de dades"],
    ["Què fa el protocol HTTPS?", "Xifrat la connexió web", "Imprimeix pàgines", "Descarrega fitxers", "Controla el maquinari"],
    ["Què és el blockchain?", "Registre distribuït", "Tipus de xarxa social", "Dispositiu de memòria", "Sistema operatiu"],
    ["Què és la realitat virtual?", "Entorn generat per ordinador", "Còpia de seguretat", "Tipus de programari", "Video real"],
    ["Què és el 5G?", "Tecnologia de xarxa mòbil", "Servei de streaming", "Tipus de malware", "Assistència virtual"],
    ["Què és Linux?", "Sistema operatiu", "Aplicació", "Navegador web", "Llenguatge de programació"],
    ["Què és Python?", "Llenguatge de programació", "Base de dades", "Sistema operatiu", "Xarxa social"],
    ["Què és un drone?", "Robot volador", "Tipus de cable", "Aplicació d’ordinador", "Programari maliciós"],
    ["Què és el USB-C?", "Nova connexió universal", "Versió antiga d’USB", "Sistema operatiu", "Programari"],
    ["Què és la intel·ligència artificial generativa?", "Models que generen contingut", "Crear art intel·lectual", "Virus informàtic", "Xarxa social"],
    ["Què és l’e-commerce?", "Venda en línia", "Sistema operatiu", "Tipus de programari", "Disc local"],
]

ResCorTec = [
    "Central Processing Unit",
    "Memòria de treball",
    "Gestiona recursos del PC",
    "Adreça d’internet",
    "Connexió inalàmbrica",
    "Servei en el núvol",
    "Protegeix de programari maliciós",
    "Universal Serial Bus",
    "Llenguatge de marcat",
    "Mostrar pàgines web",
    "Processador gràfic",
    "Disc dur d’estat sòlid",
    "Nova versió de HTML",
    "Artificial Intelligence",
    "Internet of Things",
    "Programa de seguretat",
    "Connexió inalàmbrica curta distància",
    "Adreça web",
    "Llenguatge de marcat",
    "Xifrat la connexió web",
    "Registre distribuït",
    "Entorn generat per ordinador",
    "Tecnologia de xarxa mòbil",
    "Sistema operatiu",
    "Llenguatge de programació",
    "Robot volador",
    "Nova connexió universal",
    "Models que generen contingut",
    "Venda en línia",
]
