PreResTec = [
    ["Què significa CPU?", "Central Power Unit", "Central Processing Unit", "Computer Performance Unit", "Central Program Unit"],
    ["Què és la RAM?", "Memòria permanent", "Memòria de treball", "Dispositiu de xarxa", "Targeta gràfica"],
    ["Què fa el sistema operatiu Windows?", "Crea vídeos", "Gestiona recursos del PC", "Dissenya webs", "Imprimeix"],
    ["Què és una IP?", "Adreça d’internet", "Impressora personal", "Programació instantània", "Interfície pública"],
    ["Què és el Wi‑Fi?", "Emissió de ràdio", "Connexió inalàmbrica", "Dispositiu d’emmagatzematge", "Tipus de virus"],
    ["Què és 'cloud computing'?", "Emmagatzematge local", "Servei en el núvol", "Sistema operatiu", "Maquinari físic"],
    ["Què fa un antivirus?", "Copia arxius", "Protegeix de programari maliciós", "Augmenta memòria", "Millora processador"],
    ["Què significa USB?", "Universal Serial Bus", "Universal Software Bus", "Unique Serial Bus", "Universal System Backup"],
    ["Què és HTML?", "Llenguatge de programació", "Llenguatge de marcat", "Base de dades", "Sistema operatiu"],
    ["Per a què serveix un navegador?", "Emmagatzemar dades", "Mostrar pàgines web", "Edita imatges", "Envia correu"],
    ["Què és la GPU?", "Processador gràfic", "Memòria ràpida", "Dispositiu d’àudio", "Sensor"],
    ["Què és un SSD?", "Disc dur mecànic", "Disc dur d’estat sòlid", "Targeta de xarxa", "Font d’alimentació"],
    ["Què és HTML5?", "Nova versió de HTML", "Servei web", "Llenguatge de programació", "Sistema operatiu"],
    ["Què significa 'AI'?", "Artificial Intelligence", "Automated Interface", "Audio Input", "Advanced Internet"],
    ["Què és l’IOT?", "Internet of Things", "Integration of Technology", "International Organization of Telecom", "Interface of Things"],
    ["Què és un firewall?", "Tallafocs", "Programa de seguretat", "Virus informàtic", "Maquinari d’àudio"],
    ["Per a què serveix 'Bluetooth'?", "Connexió per cable", "Connexió inalàmbrica curta distància", "Adreça IP", "Sistema operatiu"],
    ["Què és una URL?", "Adreça web", "Llenguatge de marcat", "Base de dades", "Sistema operatiu"],
    ["Què és el HTML?", "Llenguatge de marcat", "Sistema operatiu", "Programari maliciós", "Base de dades"],
    ["Què fa el protocol HTTPS?", "Descarrega fitxers", "Xifrat la connexió web", "Imprimeix pàgines", "Controla el maquinari"],
    ["Què és el blockchain?", "Tipus de xarxa social", "Registre distribuït", "Sistema operatiu", "Dispositiu de memòria"],
    ["Què és la realitat virtual?", "Video real", "Entorn generat per ordinador", "Còpia de seguretat", "Tipus de programari"],
    ["Què és el 5G?", "Assistència virtual", "Tecnologia de xarxa mòbil", "Servei de streaming", "Tipus de malware"],
    ["Què és Linux?", "Sistema operatiu", "Llenguatge de programació", "Navegador web", "Aplicació"],
    ["Què és Python?", "Base de dades", "Llenguatge de programació", "Sistema operatiu", "Xarxa social"],
    ["Què és un drone?", "Robot volador", "Aplicació d’ordinador", "Programari maliciós", "Tipus de cable"],
    ["Què és el USB-C?", "Versió antiga d’USB", "Nova connexió universal", "Sistema operatiu", "Programari"],
    ["Què és la intel·ligència artificial generativa?", "Crear art intel·lectual", "Models que generen contingut", "Virus informàtic", "Xarxa social"],
    ["Què és l’e-commerce?", "Venda en línia", "Disc local", "Sistema operatiu", "Tipus de programari"],
]

ResCorTec = [
    "Central Processing Unit",
    "Memòria de treball",
    "Gestiona recursos del PC",
    "Adreça d’internet",
    "Connexió inalàmbrica",
    "Servei en el núvol",
    "Protegeix de programari maliciós",
    "Universal Serial Bus",
    "Llenguatge de marcat",
    "Mostrar pàgines web",
    "Processador gràfic",
    "Disc dur d’estat sòlid",
    "Nova versió de HTML",
    "Artificial Intelligence",
    "Internet of Things",
    "Programa de seguretat",
    "Connexió inalàmbrica curta distància",
    "Adreça web",
    "Llenguatge de marcat",
    "Xifrat la connexió web",
    "Registre distribuït",
    "Entorn generat per ordinador",
    "Tecnologia de xarxa mòbil",
    "Sistema operatiu",
    "Llenguatge de programació",
    "Robot volador",
    "Nova connexió universal",
    "Models que generen contingut",
    "Venda en línia",
]
