PreResTec = [
    ["Què significa CPU?", "Central Processing Unit", "Central Power Unit", "Computer Performance Unit", "Central Program Unit"],
    ["Què és la RAM?", "Memòria de treball", "Dispositiu de xarxa", "Memòria permanent", "Targeta gràfica"],
    ["Què fa el sistema operatiu Windows?", "Gestiona recursos del PC", "Imprimeix", "Crea vídeos", "Dissenya webs"],
    ["Què és una IP?", "Programació instantània", "Impressora personal", "Adreça d’internet", "Interfície pública"],
    ["Què és el Wi‑Fi?", "Connexió inalàmbrica", "Tipus de virus", "Emissió de ràdio", "Dispositiu d’emmagatzematge"],
    ["Què és 'cloud computing'?", "Servei en el núvol", "Sistema operatiu", "Maquinari físic", "Emmagatzematge local"],
    ["Què fa un antivirus?", "Protegeix de programari maliciós", "Augmenta memòria", "Copia arxius", "Millora processador"],
    ["Què significa USB?", "Universal Serial Bus", "Universal System Backup", "Unique Serial Bus", "Universal Software Bus"],
    ["Què és HTML?", "Llenguatge de marcat", "Sistema operatiu", "Base de dades", "Llenguatge de programació"],
    ["Per a què serveix un navegador?", "Mostrar pàgines web", "Edita imatges", "Emmagatzemar dades", "Envia correu"],
    ["Què és la GPU?", "Memòria ràpida", "Sensor", "Dispositiu d’àudio", "Processador gràfic"],
    ["Què és un SSD?", "Disc dur d’estat sòlid", "Disc dur mecànic", "Font d’alimentació", "Targeta de xarxa"],
    ["Què és HTML5?", "Nova versió de HTML", "Servei web", "Llenguatge de programació", "Sistema operatiu"],
    ["Què significa 'AI'?", "Artificial Intelligence", "Audio Input", "Advanced Internet", "Automated Interface"],
    ["Què és l’IOT?", "Internet of Things", "Integration of Technology", "Interface of Things", "International Organization of Telecom"],
    ["Què és un firewall?", "Programa de seguretat", "Tallafocs", "Maquinari d’àudio", "Virus informàtic"],
    ["Per a què serveix 'Bluetooth'?", "Connexió inalàmbrica curta distància", "Adreça IP", "Connexió per cable", "Sistema operatiu"],
    ["Què és una URL?", "Llenguatge de marcat", "Sistema operatiu", "Adreça web", "Base de dades"],
    ["Què és el HTML?", "Llenguatge de marcat", "Sistema operatiu", "Base de dades", "Programari maliciós"],
    ["Què fa el protocol HTTPS?", "Xifrat la connexió web", "Imprimeix pàgines", "Descarrega fitxers", "Controla el maquinari"],
    ["Què és el blockchain?", "Registre distribuït", "Tipus de xarxa social", "Dispositiu de memòria", "Sistema operatiu"],
    ["Què és la realitat virtual?", "Entorn generat per ordinador", "Còpia de seguretat", "Tipus de programari", "Video real"],
    ["Què és el 5G?", "Tecnologia de xarxa mòbil", "Servei de streaming", "Tipus de malware", "Assistència virtual"],
    ["Què és Linux?", "Sistema operatiu", "Aplicació", "Navegador web", "Llenguatge de programació"],
    ["Què és Python?", "Llenguatge de programació", "Base de dades", "Xarxa social", "Sistema operatiu"],
    ["Què és un drone?", "Robot volador", "Tipus de cable", "Programari maliciós", "Aplicació d’ordinador"],
    ["Què és el USB-C?", "Nova connexió universal", "Versió antiga d’USB", "Programari", "Sistema operatiu"],
    ["Què és la intel·ligència artificial generativa?", "Models que generen contingut", "Crear art intel·lectual", "Xarxa social", "Virus informàtic"],
    ["Què és l’e-commerce?", "Venda en línia", "Sistema operatiu", "Tipus de programari", "Disc local"],
]

ResCorTec = [
    "Central Processing Unit",
    "Memòria de treball",
    "Gestiona recursos del PC",
    "Adreça d’internet",
    "Connexió inalàmbrica",
    "Servei en el núvol",
    "Protegeix de programari maliciós",
    "Universal Serial Bus",
    "Llenguatge de marcat",
    "Mostrar pàgines web",
    "Processador gràfic",
    "Disc dur d’estat sòlid",
    "Nova versió de HTML",
    "Artificial Intelligence",
    "Internet of Things",
    "Programa de seguretat",
    "Connexió inalàmbrica curta distància",
    "Adreça web",
    "Llenguatge de marcat",
    "Xifrat la connexió web",
    "Registre distribuït",
    "Entorn generat per ordinador",
    "Tecnologia de xarxa mòbil",
    "Sistema operatiu",
    "Llenguatge de programació",
    "Robot volador",
    "Nova connexió universal",
    "Models que generen contingut",
    "Venda en línia",
]
