PreResHist = [
    ["Qui va ser el primer emperador romà?", "Juli Cèsar", "August", "Neró", "Marc Antoni"],
    ["En quin any va caure l’Imperi Romà d’Occident?", "410", "476", "500", "455"],
    ["Qui va descobrir Amèrica el 1492?", "Vasco da Gama", "Cristòfor Colom", "Magallanes", "Vasco Núñez"],
    ["Quin esdeveniment va començar el 14 de juliol de 1789?", "Revolució Americana", "Revolució Francesa", "Primera Guerra Mundial", "Segona Guerra Mundial"],
    ["Qui va ser reina d’Anglaterra durant l’Edat Mitjana?", "Isabel I", "Victòria", "Elisabet II", "Matilde de Cançó"],
    ["En quin any va començar la I Guerra Mundial?", "1914", "1939", "1920", "1918"],
    ["Qui era líder del partit feixista a Itàlia?", "Hitler", "Mussolini", "Stalin", "Franco"],
    ["Quin imperi va construir Angkor Wat?", "Maià", "Khmer", "Inca", "Aztec"],
    ["Quan va caure el Mur de Berlín?", "1989", "1979", "1991", "1985"],
    ["Qui va liderar la revolució cubana?", "Fidel Castro", "Che Guevara", "Raúl Castro", "Hugo Chávez"],
    ["En quin any va independitzar-se l’Índia del Regne Unit?", "1947", "1950", "1935", "1960"],
    ["Qui va escriure 'El Manifest Comunista'?", "Lenin", "Marx i Engels", "Trotski", "Stalin"],
    ["Quin país va bombardejar Hiroshima el 1945?", "Alemanya", "Japó", "Estats Units", "Unió Soviètica"],
    ["Qui va ser la primera dona en volar sola a través de l’Atlàntic?", "Amelia Earhart", "Valentina Tereshkova", "Sally Ride", "Jacqueline Cochran"],
    ["En quin any va caure Constantinoble?", "1453", "1492", "1325", "1517"],
    ["Qui va ser el líder de l’Alemanya nazi?", "Hitler", "Goebbels", "Stalin", "Churchill"],
    ["Quan va acabar la Guerra de Secessió dels EUA?", "1865", "1848", "1901", "1910"],
    ["Qui va ser George Washington?", "Primer president dels EUA", "General romà", "Astronauta", "Filòsof grec"],
    ["Quin explorador va donar el seu nom a l’estret entre Europa i Àsia?", "Magallanes", "Colom", "Bering", "Cook"],
    ["Quan va començar la Revolució Industrial?", "Segle XVIII", "Segle XVII", "Segle XIX", "Segle XX"],
    ["Què va ser l’Imperi Otomà?", "Imperi africà", "Imperi europeu", "Imperi asiàtic", "Imperi africà i europeu"],
    ["Qui va signar l’armistici de la Primera Guerra Mundial?", "Winston Churchill", "Franz Ferdinand", "Generals aliats i alemanys", "Hitler"],
    ["Quin país va ser separat després de la guerra civil de 1949 (Xina)?", "Taiwan", "Mongòlia", "Corea del Nord", "Corea del Sud"],
    ["Qui va idear la democràcia a l’antiga Grècia?", "Plató", "Sòcrates", "Clístenes", "Aristòtil"],
    ["En quin any va esclatar la Revolució Russa?", "1917", "1905", "1922", "1933"],
    ["Què va començar el 1936 a Espanya?", "Guerra Civil", "Dictadura de Franco", "Monarquia", "Segona República"],
    ["Quina ciutat va ser el centre de l’Imperi Bizantí?", "Roma", "Constantinoble", "Atenes", "Jerusalem"],
    ["Qui va escriure 'Les Mil i Una Nits'?", "Anonim", "Shahrazad", "Goethe", "Shakespeare"],
    ["Quan va ser la caiguda de l’Imperi Mongol?", "XIII segle", "XV segle", "XIV segle", "XII segle"],
    ["Quin tractat va acabar la Guerra dels Trenta Anys (1648)?", "Pau de Versalles", "Tractat de Westfàlia", "Tractat de Viena", "Pau d’Utrecht"],
]

ResCorHist = [
    "August",
    "476",
    "Cristòfor Colom",
    "Revolució Francesa",
    "Matilde de Cançó",
    "1914",
    "Mussolini",
    "Khmer",
    "1989",
    "Fidel Castro",
    "1947",
    "Marx i Engels",
    "Estats Units",
    "Amelia Earhart",
    "1453",
    "Hitler",
    "1865",
    "Primer president dels EUA",
    "Bering",
    "Segle XVIII",
    "Imperi europeu",
    "Generals aliats i alemanys",
    "Taiwan",
    "Clístenes",
    "1917",
    "Guerra Civil",
    "Constantinoble",
    "Shahrazad",
    "XIV segle",
    "Tractat de Westfàlia",
]
