PreResGeo = [
    ["Quina és la capital d’Alemanya?", "Berlín", "Frankfurt", "Munic", "Hamburg"],
    ["Quin país té la ciutat de Sydney?", "Austràlia", "Canadà", "Nou Zelanda", "Sud-àfrica"],
    ["Quin és el continent més gran?", "Àsia", "Europa", "Amèrica del Sud", "Àfrica"],
    ["Quin oceà és el més profund?", "Pacífic", "Àrtic", "Atlàntic", "Índic"],
    ["Quina és la muntanya més alta d’Àfrica?", "Kilimanjaro", "Atlas", "Montserrat", "Kenya"],
    ["Quina és la capital del Brasil?", "Brasília", "Salvador", "Rio de Janeiro", "São Paulo"],
    ["Quin riu travessa París?", "Sena", "Tàmesi", "Danubi", "Rin"],
    ["Quin país té la major població?", "Xina", "Estats Units", "Indonèsia", "Índia"],
    ["Quina és la capital de Japó?", "Tòquio", "Kioto", "Osaka", "Tokio"],
    ["Quants oceans hi ha al món?", "5", "7", "6", "4"],
    ["Quina és la península més gran del món?", "Aràbiga", "Escandinava", "Indo-xinesa", "Ibèrica"],
    ["Quina ciutat es diu 'ciutat eterna'?", "Roma", "París", "Jerusalem", "Atenes"],
    ["On es troba la Gran Muralla Xinesa?", "Xina", "Corea", "Mongòlia", "Japó"],
    ["Quina és la capital d’Egipte?", "Pretòria", "Gizeh", "El Caire", "Alexandria"],
    ["Quina és la capital de Sud-àfrica?", "Pretòria", "Ciutat del Cap", "Durban", "Johannesburg"],
    ["Quin país està entre França i Espanya?", "Andorra", "Bèlgica", "Portugal", "Itàlia"],
    ["Quin mar limita amb la Costa Brava?", "Mar Mediterrani", "Mar Egeu", "Mar Roig", "Mar Cantàbric"],
    ["Quina és la capital de Mèxic?", "Ciudad de Mèxic", "Monterrey", "Cancún", "Guadalajara"],
    ["Quin país té la forma d’un triangle invertit (Índia)?", "Índia", "Bangladesh", "Nepal", "Pakistan"],
    ["Quina és la capital de Turquia?", "Ankara", "Antalya", "Esmirna", "Istanbul"],
    ["Quants estats té Estats Units?", "50", "52", "49", "51"],
    ["Quina és la muntanya més alta del món?", "Everest", "Kanchenjunga", "Lhotse", "K2"],
    ["Quina és la capital d’Itàlia?", "Roma", "Florència", "Venècia", "Milà"],
    ["En quin oceà es troba Madagascar?", "Índic", "Pacífic", "Àrtic", "Atlàntic"],
    ["Quina és la capital de Rússia?", "Moscou", "Kazan", "Novosibirsk", "Sant Petersburg"],
    ["Quin país té capitals separades (llegislativa i administrativa)?", "Sud-àfrica", "Xina", "Brasil", "Estats Units"],
    ["Quina és la capital de Corea del Sud?", "Seül", "Daegu", "Incheon", "Busan"],
    ["Quin mar banya la costa de Galícia?", "Atlàntic", "Roig", "Mediterrani", "Cantàbric"],
    ["Quin país té el desert del Gobi?", "Mongòlia", "Índia", "Pakistan", "Xina"],
    ["Quina és la capital d’Argentina?", "Buenos Aires", "Mendoza", "Còrdova", "Rosario"],
    ["Quin país té la forma d’un bota?", "Itàlia", "Grècia", "Portugal", "Espanya"],
    ["Quina és la ciutat més poblada del món?", "Tokio", "São Paulo", "Xangai", "Delhi"],
]

ResCorGeo = [
    "Berlín",
    "Austràlia",
    "Àsia",
    "Pacífic",
    "Kilimanjaro",
    "Brasília",
    "Sena",
    "Xina",
    "Tòquio",
    "5",
    "Aràbiga",
    "Roma",
    "Xina",
    "Pretòria",
    "Andorra",
    "Mar Mediterrani",
    "Ciudad de Mèxic",
    "Índia",
    "Ankara",
    "50",
    "Everest",
    "Roma",
    "Índic",
    "Moscou",
    "Sud-àfrica",
    "Seül",
    "Atlàntic",
    "Mongòlia",
    "Buenos Aires",
    "Itàlia",
    "Tokio",
]