PreResEsport = [
    ["Quants jugadors té un equip de futbol?", "11", "12", "9", "10"],
    ["Quina disciplina forma part dels Jocs Olímpics?", "Futbol", "Escacs", "Bàsquet", "Pòquer"],
    ["Quin és el principal objectiu del ioga?", "Relaxació i força", "Competir", "Ganar múscul", "Córrer ràpid"],
    ["En quin esport es fa servir una raqueta?", "Tennis", "Rem", "Futbol", "Hoquei"],
    ["Quants minuts dura un partit de futbol (temps regular)?", "90", "120", "70", "60"],
    ["Com es diu el moviment bàsic per nedar d’esquena?", "Esquena", "Braça", "Crol", "Papallona"],
    ["Quants jugadors hi ha en bàsquet per equip al camp?", "5", "7", "4", "6"],
    ["Què és el dopatge?", "Consum de substàncies il·legals", "Reforç mental", "Entrenament", "Suport"],
    ["Qui va guanyar més medalles olímpiques?", "Michael Phelps", "Simone Biles", "Nadal", "Usain Bolt"],
    ["En quin esport s'utilitza una pista de 400 m?", "Atletisme", "Natació", "Tennis", "Futbol"],
    ["En quin esport s'utilitza un tatami?", "Judo", "Futbol sala", "Rugbi", "Boxa"],
    ["Què és el fair play?", "Joc net", "Celebrar massa", "Fer trampes", "Empènyer el rival"],
    ["Què treballa la flexibilitat?", "Mobilitat articular", "Velocitat", "Força", "Resistència"],
    ["Quina part del cos impulsa la carrera?", "Cames", "Coll", "Braços", "Peus"],
    ["Quin esport es juga sobre gel?", "Patinatge artístic", "Handbol", "Voleibol", "Esquí aquàtic"],
    ["Quin és l'esport que es juga amb una cistella?", "Bàsquet", "Hoquei", "Rugbi", "Futbol"],
    ["Què mesura el cronòmetre?", "Temps", "Força", "Alçada", "Distància"],
    ["Quin esport es practica amb una bicicleta?", "Ciclisme", "Judo", "Rem", "Esgrima"],
    ["Com es diu el salt sense córrer?", "Salt vertical", "Salt de potència", "Salt d’alçada", "Salt de llargada"],
    ["Quin tipus d’esport és la marató?", "Fons", "Salt", "Velocitat", "Força"],
    ["Què és la coordinació?", "Sincronitzar moviments", "Aixecar pes", "Fer salts", "Córrer ràpid"],
    ["Quin esport inclou disciplines com espasa i sabre?", "Esgrima", "Atletisme", "Lluita", "Rem"],
    ["Quants segons tens per servir en tennis?", "25", "5", "10", "15"],
    ["Què és un estirament?", "Acció per millorar flexibilitat", "Carrera ràpida", "Moviment violent", "Recolzament"],
    ["Quin esport es juga amb una pilota ovalada?", "Rugbi", "Tennis", "Futbol sala", "Bàsquet"],
    ["Quin esport es practica amb cavalls?", "Equitació", "Esgrima", "Ciclisme", "Jòquei"],
    ["Què és el fons físic?", "Resistència llarga", "Potència curta", "Velocitat màxima", "Poc esforç"],
    ["En quin esport es fa servir un casc i una bici?", "Ciclisme", "Rugbi", "Hípica", "Esgrima"],
    ["Quin esport es juga amb pals i porteries sobre gel?", "Hòquei sobre gel", "Esgrima", "Bàsquet", "Hoquei herba"],
    ["Quin esport és olímpic d’estiu?", "Esgrima", "Trineu", "Esquí", "Snowboard"],
]

ResCorEsport = [
    "11", "Futbol", "Relaxació i força", "Tennis", "90", "Esquena", "5", "Consum de substàncies il·legals", "Michael Phelps", "Atletisme",
    "Judo", "Joc net", "Mobilitat articular", "Cames", "Patinatge artístic", "Bàsquet", "Temps", "Ciclisme", "Salt vertical", "Fons",
    "Sincronitzar moviments", "Esgrima", "25", "Acció per millorar flexibilitat", "Rugbi", "Equitació", "Resistència llarga", "Ciclisme", "Hòquei sobre gel", "Esgrima"
]