PreResGeo = [
    ["Quina és la capital d’Alemanya?", "Munic", "Hamburg", "Frankfurt", "Berlín"],
    ["Quin país té la ciutat de Sydney?", "Nou Zelanda", "Austràlia", "Canadà", "Sud-àfrica"],
    ["Quin és el continent més gran?", "Àfrica", "Àsia", "Europa", "Amèrica del Sud"],
    ["Quin oceà és el més profund?", "Atlàntic", "Índic", "Pacífic", "Àrtic"],
    ["Quina és la muntanya més alta d’Àfrica?", "Kenya", "Kilimanjaro", "Montserrat", "Atlas"],
    ["Quina és la capital del Brasil?", "Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
    ["Quin riu travessa París?", "Rin", "Danubi", "Tàmesi", "Sena"],
    ["Quin país té la major població?", "Índia", "Xina", "Estats Units", "Indonèsia"],
    ["Quina és la capital de Japó?", "Osaka", "Tokio", "Tòquio", "Kioto"],
    ["Quants oceans hi ha al món?", "4", "5", "6", "7"],
    ["Quina és la península més gran del món?", "Aràbiga", "Ibèrica", "Indo-xinesa", "Escandinava"],
    ["Quina ciutat es diu 'ciutat eterna'?", "Roma", "Atenes", "Jerusalem", "París"],
    ["On es troba la Gran Muralla Xinesa?", "Xina", "Japó", "Mongòlia", "Corea"],
    ["Quina és la capital d’Egipte?", "El Caire", "Alexandria", "Luxor", "Gizeh"],
    ["Quina és la capital de Sud-àfrica?", "Johannesburg", "Pretòria", "Ciutat del Cap", "Durban"],
    ["Quin país està entre França i Espanya?", "Itàlia", "Andorra", "Portugal", "Bèlgica"],
    ["Quin mar limita amb la Costa Brava?", "Mar Mediterrani", "Mar Cantàbric", "Mar Egeu", "Mar Roig"],
    ["Quina és la capital de Mèxic?", "Guadalajara", "Monterrey", "Ciudad de Mèxic", "Cancún"],
    ["Quin país té la forma d’un triangle invertit (Índia)?", "Índia", "Bangladesh", "Pakistan", "Nepal"],
    ["Quina és la capital de Turquia?", "Istanbul", "Ankara", "Esmirna", "Antalya"],
    ["Quants estats té Estats Units?", "50", "51", "49", "52"],
    ["Quina és la muntanya més alta del món?", "K2", "Everest", "Kanchenjunga", "Lhotse"],
    ["Quina és la capital d’Itàlia?", "Milà", "Roma", "Venècia", "Florència"],
    ["En quin oceà es troba Madagascar?", "Atlàntic", "Índic", "Pacífic", "Àrtic"],
    ["Quina és la capital de Rússia?", "Sant Petersburg", "Moscou", "Novosibirsk", "Kazan"],
    ["Quin país té capitals separades (llegislativa i administrativa)?", "Sud-àfrica", "Estats Units", "Brasil", "Xina"],
    ["Quina és la capital de Corea del Sud?", "Seül", "Busan", "Incheon", "Daegu"],
    ["Quin mar banya la costa de Galícia?", "Atlàntic", "Cantàbric", "Mediterrani", "Roig"],
    ["Quin país té el desert del Gobi?", "Xina", "Índia", "Mongòlia", "Pakistan"],
    ["Quina és la capital d’Argentina?", "Còrdova", "Rosario", "Buenos Aires", "Mendoza"],
    ["Quin país té la forma d’un bota?", "Itàlia", "Grècia", "Espanya", "Portugal"],
    ["Quina és la ciutat més poblada del món?", "Tokio", "Delhi", "Xangai", "São Paulo"],
]

ResCorGeo = [
    "Berlín",
    "Austràlia",
    "Àsia",
    "Pacífic",
    "Kilimanjaro",
    "Brasília",
    "Sena",
    "Xina",
    "Tòquio",
    "5",
    "Aràbiga",
    "Roma",
    "Xina",
    "Pretòria",
    "Andorra",
    "Mar Mediterrani",
    "Ciudad de Mèxic",
    "Índia",
    "Ankara",
    "50",
    "Everest",
    "Roma",
    "Índic",
    "Moscou",
    "Sud-àfrica",
    "Seül",
    "Atlàntic",
    "Mongòlia",
    "Buenos Aires",
    "Itàlia",
    "Tokio",
]
